version: v2.{build}

image: Visual Studio 2017

build:

  verbosity: minimal

deploy:

- provider: FTP

  host: zyriangaming.com

  protocol: ftp

  username: Julian

  password:

    secure: cvMkH7Q3A1k77UEwAKYX2A==

  active_mode: true
