version: v2.78913

image: Visual Studio 2017

build:

  verbosity: minimal

artifacts:
7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\path\to\bin\*.dll

deploy:

- provider: FTP

  host: zyriangaming.com

  protocol: ftp

  username: Julian

  password:

    secure: cvMkH7Q3A1k77UEwAKYX2A==

  active_mode: true
