version: v2.15
image: Visual Studio 2017
build:
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: eefe37ea4e3fb98e87c8b88bb22eb397e987439a
  artifact: lambdamenu
  force_update: true
